-- 020_client_reports.sql
-- Monthly GEO performance reports, one per brand per CALENDAR month (YYYY-MM). A report is
-- generated by an SDK session (the geo-site-report skill), which pulls AI-mention counts,
-- backlinks and referring domains from DataForSEO and grounds findings with Firecrawl, then
-- writes report.json + a branded PDF. The engine commits BOTH into a client_reports row.
--
-- THE SHARING MODEL, which is the whole reason this table has two halves:
--   * The WORKING copy (report, pdf, generated_at) is the operator's. It is what the admin
--     dashboard shows, what a PDF download serves, and what Delete removes. A brand holds at
--     most ONE working report per month: regenerating means Delete first, then Generate.
--   * The SHARED snapshot (shared_report, shared_pdf, shared_at) is the client's. Share copies
--     the working copy into it. It is IMMUTABLE by Generate and survives a Delete of the
--     working copy, so a client keeps seeing the last report the operator sent even after the
--     operator deletes and is mid-regenerating this month's. Re-sharing overwrites it.
-- Deleting the working copy NEVER touches the shared snapshot: "delete will not delete it for
-- the client". Regenerating after a share leaves generated_at > shared_at, which the app reads
-- as "not shared with the client yet".
--
-- ACCESS. RLS is enabled and EVERY authenticated grant is revoked, so a client's own JWT
-- cannot read report / pdf (operator material) or another brand's row over PostgREST at all.
-- The two paths that legitimately read are:
--   * the LOCAL engine, over the owner connection (server/db.py), which bypasses RLS: it owns
--     generate / list / share / delete / pdf for the operator, exactly like every other write.
--   * the HOSTED site, over PostgREST, ONLY through the SECURITY DEFINER functions below:
--     report_months / report_pdf (client, shared snapshot only, membership-scoped) and
--     admin_report_months / admin_report_pdf (hosted admin preview, auth_is_admin()). The
--     hosted site performs NO report write; generate / share / delete are refused there and
--     happen in the Canon app, the same rule every admin write already follows.
--
-- Idempotent guards throughout; schema.sql folds this same final state in for fresh builds.
--
--   .venv/bin/python supabase/apply.py supabase/migrations/020_client_reports.sql

begin;

create table if not exists client_reports (
  id            uuid primary key default gen_random_uuid(),
  client_id     uuid not null references clients(id) on delete cascade,
  -- Calendar month, not a sequence label (roadmap_sheets.month is the sequence one). The
  -- check keeps the format the app parses and orders by as a plain string.
  month         text not null check (month ~ '^\d{4}-(0[1-9]|1[0-2])$'),

  -- The working copy: the operator's, nulled by Delete.
  report        jsonb,
  pdf           bytea,
  generated_at  timestamptz,
  generated_by  text,

  -- The shared snapshot: the client's, set by Share, untouched by Generate and Delete.
  shared_report jsonb,
  shared_pdf    bytea,
  shared_at     timestamptz,
  shared_by     text,

  created_at    timestamptz not null default now(),

  unique (client_id, month)
);

create index if not exists client_reports_client on client_reports (client_id);

-- Supabase grants every new public table to authenticated by default, so close it explicitly:
-- nothing reads this table over PostgREST except the definer functions below.
alter table client_reports enable row level security;
revoke all on client_reports from authenticated, anon;

-- ---------------------------------------------------------------------------
-- Client read: the SHARED snapshot only, membership-scoped, shared_at not null.
-- Returns one object per month that has ever been shared, newest first. Never returns the
-- working copy and never the pdf bytes (report_pdf serves those). A brand with nothing shared
-- returns an empty array, which the portal renders as "no reports available yet".
-- ---------------------------------------------------------------------------
create or replace function report_months(p_brand text)
returns jsonb
language sql
stable
security definer
set search_path to 'public'
as $$
  select coalesce(jsonb_agg(
           jsonb_build_object('month', r.month, 'shared_at', r.shared_at,
                              'report', r.shared_report, 'has_pdf', (r.shared_pdf is not null))
           order by r.month desc), '[]'::jsonb)
  from client_reports r
  join clients c on c.id = r.client_id
  where c.slug = p_brand
    and r.shared_at is not null
    and r.shared_report is not null
    and auth_can_read_client_slug(p_brand);
$$;

-- Client PDF: the shared snapshot's PDF for one month, or NULL when nothing is shared there.
create or replace function report_pdf(p_brand text, p_month text)
returns bytea
language sql
stable
security definer
set search_path to 'public'
as $$
  select r.shared_pdf
  from client_reports r
  join clients c on c.id = r.client_id
  where c.slug = p_brand
    and r.month = p_month
    and r.shared_at is not null
    and auth_can_read_client_slug(p_brand);
$$;

-- ---------------------------------------------------------------------------
-- Admin read (hosted preview): every month this brand holds, with the WORKING report where one
-- exists (null on a month whose working copy was deleted, so a deleted report stays unseeable),
-- plus the shared-snapshot flags so the dashboard can label shared / not-shared / deleted.
-- ---------------------------------------------------------------------------
create or replace function admin_report_months(p_brand text)
returns jsonb
language sql
stable
security definer
set search_path to 'public'
as $$
  select coalesce(jsonb_agg(
           jsonb_build_object(
             'month', r.month,
             'report', r.report,
             'has_pdf', (r.pdf is not null),
             'generated_at', r.generated_at,
             'generated_by', r.generated_by,
             'shared_at', r.shared_at,
             'shared_by', r.shared_by,
             'has_shared', (r.shared_report is not null))
           order by r.month desc), '[]'::jsonb)
  from client_reports r
  join clients c on c.id = r.client_id
  where c.slug = p_brand
    and auth_is_admin();
$$;

-- Admin PDF (hosted preview): the WORKING copy's PDF for one month.
create or replace function admin_report_pdf(p_brand text, p_month text)
returns bytea
language sql
stable
security definer
set search_path to 'public'
as $$
  select r.pdf
  from client_reports r
  join clients c on c.id = r.client_id
  where c.slug = p_brand
    and r.month = p_month
    and auth_is_admin();
$$;

revoke all on function report_months(text), report_pdf(text, text),
  admin_report_months(text), admin_report_pdf(text, text) from public, anon;
grant execute on function report_months(text), report_pdf(text, text),
  admin_report_months(text), admin_report_pdf(text, text) to authenticated;

commit;
