-- 027_client_analyses.sql
-- Monthly ANALYSIS reports, one per brand per CALENDAR month (YYYY-MM). An analysis is generated by
-- an SDK session (the geo-analysis-report skill), which merges up to six tools (DataForSEO, SEO
-- Gets, Google Search Console, Bing Webmaster, Google Analytics, Microsoft Clarity) plus own LLM
-- prompt-test runs into ONE normalized analysis.json, then renders a branded PDF. The engine commits
-- BOTH into a client_analyses row.
--
-- The table is shaped like client_reports (020) on purpose, WORKING half plus a SHARED snapshot,
-- so the same generate / list / delete / pdf plumbing clones cleanly and a future share-to-client
-- needs no migration:
--   * The WORKING copy (analysis, pdf, generated_at) is the operator's. It is what the admin
--     Analysis tab shows, what a PDF download serves, and what Delete removes. One working analysis
--     per brand per month: regenerating means Delete first, then Run.
--   * The SHARED snapshot (shared_analysis, shared_pdf, shared_at) is reserved for a future
--     share-to-client act. It is IMMUTABLE by generation and survives a Delete of the working copy.
--     No route writes it yet; it exists so adding Share later is a route, not a schema change.
--
-- ACCESS. RLS is enabled and EVERY authenticated grant is revoked, so no client JWT can read this
-- table over PostgREST at all. The only reader today is the LOCAL engine, over the owner connection
-- (server/db.py), which bypasses RLS: it owns generate / list / delete / pdf for the operator. If a
-- hosted (PostgREST) read is ever needed, add SECURITY DEFINER functions here exactly as 020 did
-- for reports; none are added now because no hosted route calls them yet (dead SQL otherwise).
--
-- Idempotent guards throughout; schema.sql folds this same final state in for fresh builds.
--
--   .venv/bin/python supabase/apply.py supabase/migrations/027_client_analyses.sql

begin;

create table if not exists client_analyses (
  id             uuid primary key default gen_random_uuid(),
  client_id      uuid not null references clients(id) on delete cascade,
  -- Calendar month, same format the app parses and orders by as a plain string.
  month          text not null check (month ~ '^\d{4}-(0[1-9]|1[0-2])$'),

  -- The working copy: the operator's, nulled by Delete.
  analysis       jsonb,
  pdf            bytea,
  generated_at   timestamptz,
  generated_by   text,

  -- The shared snapshot: reserved for a future share-to-client act, untouched by Generate/Delete.
  shared_analysis jsonb,
  shared_pdf      bytea,
  shared_at       timestamptz,
  shared_by       text,

  created_at     timestamptz not null default now(),

  unique (client_id, month)
);

create index if not exists client_analyses_client on client_analyses (client_id);

-- Supabase grants every new public table to authenticated by default, so close it explicitly:
-- nothing reads this table over PostgREST. The engine reads it over the owner connection.
alter table client_analyses enable row level security;
revoke all on client_analyses from authenticated, anon;

commit;
